CREATE TABLE IF NOT EXISTS addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    receiver_name character varying(120) NOT NULL,
    receiver_phone character varying(30) NOT NULL,
    address_line text NOT NULL,
    ward character varying(120) NOT NULL,
    district character varying(120) NOT NULL,
    province character varying(120) NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    CONSTRAINT addresses_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id);
