server:
  port: 8080

spring:
  application:
    name: luna-fashion-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/luna_fashion
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
