server:
  port: 8080

spring:
  application:
    name: ni-sport-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/ni_sport
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: change-this-secret-for-ni-sport-backend-jwt-signing
  expiration-minutes: 1440
